version: "3"
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zoo
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
    networks:
      - zoo-net

  clickhouse01:
    image: yandex/clickhouse-server
    container_name: clickhouse01
    volumes:
      - ./config1.xml:/etc/clickhouse-server/config.xml
      - clickhouse01_data:/var/lib/clickhouse
    ports:
      - "8123:8123" # Port for HTTP interface
      - "9000:9000" # Port for native client
    networks:
      - zoo-net

  clickhouse02:
    image: yandex/clickhouse-server
    container_name: clickhouse02
    volumes:
      - ./config2.xml:/etc/clickhouse-server/config.xml
      - clickhouse02_data:/var/lib/clickhouse
    ports:
      - "8124:8123"
      - "9001:9000"
    networks:
      - zoo-net

networks:
  zoo-net:
    driver: bridge

volumes:
  clickhouse01_data:
    driver: local
  clickhouse02_data:
    driver: local
